# Generated by Django 5.0.6 on 2024-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_options_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="category/images/",
                verbose_name="Избражение",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="category/images/",
                verbose_name="Избражение",
            ),
        ),
    ]
