# Generated by Django 5.0.6 on 2024-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_category_image_subcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="category/images/",
                verbose_name="Избражение",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="category/images/",
                verbose_name="Избражение",
            ),
        ),
    ]
