# Generated by Django 5.0.6 on 2024-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_category_created_category_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="image",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="slug",
        ),
    ]
