# Generated by Django 5.0.6 on 2024-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_remove_category_image_remove_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="category/images/",
                verbose_name="Избражение",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="category/images/",
                verbose_name="Избражение",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="slug"
            ),
        ),
    ]
