# Generated by Django 5.0.6 on 2024-07-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_category_image_alter_subcategory_image"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="category.subcategory",
                verbose_name="Подкатегория",
            ),
            preserve_default=False,
        ),
    ]
