# Generated by Django 5.0.6 on 2024-07-04 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_per_unit",
        ),
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=False, verbose_name="В наличии"),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Количество"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(limit_value=0)],
                verbose_name="Цена за единицу",
            ),
            preserve_default=False,
        ),
    ]
