# Generated by Django 5.0.6 on 2024-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_brand_country_product_brand_product_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="category/images/",
                verbose_name="Избражение",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="slug"
            ),
        ),
    ]
