# Generated by Django 5.0.6 on 2024-07-08 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_image_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="loose",
            field=models.BooleanField(default=False, verbose_name="На развес"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(limit_value=100)],
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(limit_value=0.1)],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("кг", "кг"), ("шт", "шт"), ("л", "л")],
                default="шт",
                max_length=2,
                verbose_name="Единица товара",
            ),
        ),
    ]
