# Generated by Django 5.0.6 on 2024-07-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_loose_alter_product_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
