# Generated by Django 5.0.6 on 2024-07-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_productimage_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                fields=("product", "image"), name="image"
            ),
        ),
    ]
