# Generated by Django 5.0.6 on 2024-07-09 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(limit_value=0.1)],
                verbose_name="Количество",
            ),
        ),
    ]
