# Generated by Django 5.0.6 on 2024-07-09 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(limit_value=0.1)],
                verbose_name="Длступное кол-во",
            ),
            preserve_default=False,
        ),
    ]
