# Generated by Django 5.0.6 on 2024-07-09 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_remove_product_quantity_product_stock_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(limit_value=0.0)],
                verbose_name="Длступное кол-во",
            ),
        ),
    ]
