# Generated by Django 5.0.6 on 2024-07-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_price_per_unit_product_in_stock_and_more"),
        ("shopping_carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="CartItem",
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
    ]
