# Generated by Django 5.0.6 on 2024-07-06 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Дата обновления"
            ),
        ),
    ]
