# Generated by Django 5.0.6 on 2024-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_created_product_updated"),
        ("users", "0003_shoppingcart_created_shoppingcart_updated"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("shopping_cart", "product"), name="unique_cart_product"
            ),
        ),
    ]
