# Generated by Django 5.0.6 on 2024-07-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_cartitem_unique_cart_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="total_price",
        ),
    ]
