# Generated by Django 5.0.6 on 2024-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_cartitem_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, max_digits=6, verbose_name="Количество"
            ),
        ),
    ]
